export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START';
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';
export const GOOGLE_SIGNIN_FAILURE = 'GOOGLE_SIGNIN_FAILURE';
export const GOOGLE_SIGN_OUT = "GOOGLE_SIGN_OUT";